Debug:10

diff --git a/.github/workflows/trivy.yml b/.github/workflows/trivy.yml
--- a/.github/workflows/trivy.yml
+++ b/.github/workflows/trivy.yml
@@ -36,7 +36,10 @@ jobs:
         run: |
           if ! docker pull --platform linux/amd64 ghcr.io/rajanagori/nightingale:stable; then
             echo "Docker image not found for amd64. Trying arm64."
+            if ! docker pull --platform linux/arm64 ghcr.io/rajanagori/nightingale:stable; then
+              echo "Docker image not found for arm64."
             exit 1
+          exit 1
           fi
 
       - name: Cache Trivy DB
